/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  tutorialSidebar: [
    {
      type: 'html',
      value:
        '<a class="navbar__brand sidebar__brand" href="/"><div class="navbar__logo"><img src="/img/enslogo_new.svg" alt="ENS Logo"></div>Support</a>',
        defaultStyle: true
    },
    {
      type: "html",
      className: "sidebar-divider",
      value: "<div/>"
    },
    {
      type: "category",
      label: "Core Concepts",
      link: { type: "doc", id: "core/index" },
      collapsible: false,
      collapsed: false,
      className: "CoreClass",
      items: [
        "intro",
        "core/what-is-ens",
        "core/ens-use-cases",
        {
          type: "category",
          label: "Design",
          link: { type: "doc", id: "core/design/index" },
          collapsible: true,
          collapsed: true,
          items: [
            "core/design/how-ens-works",
            "core/design/where-are-names-stored",
            "core/design/terminology",
          ],
         },
         {
          type: "category",
          label: "Registration",
          link: { type: "doc", id: "core/registration/index" },
          collapsible: true,
          collapsed: true,
          items: [
            "core/registration/registration-steps",
            "core/registration/fees",
            "core/registration/renewals",
            "core/registration/name-lifecycle",
            "core/registration/temporary-premium",
            "core/registration/integrating-dns",
          ],
         },
         {
          type: "category",
          label: "Records",
          link: { type: "doc", id: "core/records/index" },
          collapsible: true,
          collapsed: true,
          items: [
            "core/records/eth-address",
            "core/records/primary-name",
            "core/records/avatar",
            "core/records/coin-types",
            "core/records/social",
            "core/records/content-hash",
            "core/records/custom-records",
            "core/records/resolver",
          ],
        },
      ],
    },
    {
      type: "html",
      className: "sidebar-divider",
      value: "<div/>"
    },
    {
      type: "category",
      label: "Support FAQ",
      link: { type: "doc", id: "faq/index" },
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: "category",
          label: "Manager App/Site",
          link: { type: "doc", id: "faq/manager/index" },
          collapsible: true,
          collapsed: true,
          items: [
            "faq/manager/general",
            "faq/manager/registering-names",
            "faq/manager/managing-names",
            "faq/manager/troubleshooting",
            "faq/manager/v2-manager",
          ],
        },
        {
          type: "category",
          label: "Marketplaces",
          link: { type: "doc", id: "faq/marketplaces/index" },
          collapsible: true,
          collapsed: true,
          items: [
            "faq/marketplaces/opensea",
            "faq/marketplaces/ensvision",
           ],
        },
        {
          type: "category",
          label: "Wallets",
          link: { type: "doc", id: "faq/wallets/index" },
          collapsible: true,
          collapsed: true,
          items: [
            "faq/wallets/coinbase_wallet",
            "faq/wallets/ledger",
            "faq/wallets/metamask",
            "faq/wallets/metamask_mobile",
            "faq/wallets/trezor",
          ],
        },
        {
          type: "category",
          label: "Normalization",
          link: { type: "doc", id: "faq/normalization/index" },
          collapsible: true,
          collapsed: true,
          items: [
            "faq/normalization/normalization-faq",
            "faq/normalization/homoglyphs",
          ],
        },
        {
          type: "category",
          label: "Services",
          link: { type: "doc", id: "faq/services/index" },
          collapsible: true,
          collapsed: true,
          items: [
            "faq/services/twitter",
          ],
        },
        "faq/secondary_market",
        "faq/security",
        "faq/contributor-guidelines",
	      "faq/bug-bounty",
	      "faq/dnssec",
      ]
    },
    {
      type: "html",
      className: "sidebar-divider",
      value: "<div/>"
    },
    {
      type: "category",
      label: "How-To",
      link: { type: "doc", id: "howto/index" },
      collapsible: false,
      collapsed: false,
      items: [
        "howto/add-custom-record",
        "howto/add-wallet-address",
        "howto/decentralized-website",
        "howto/integrate-dns",
        "howto/registration",
        "howto/renew-names",
	      "howto/set-avatar",
        "howto/set-primary-name",
	      "howto/set-record",
        "howto/test-v3-manager",
        "howto/transfer-name",
        "howto/set-twitter-name",
        {
          type: "category",
          label: "Namewrapper",
          link: { type: "doc", id: "howto/namewrapper/index" },
          collapsible: true,
          collapsed: false,
          items: [
            "howto/namewrapper/wrap-eth-2ld",
            "howto/namewrapper/wrap-subname",
            "howto/namewrapper/change-permissions",
            "howto/namewrapper/unwrap-names",
           ],
        },
        {
          type: "category",
          label: "V2 Manager App",
          link: { type: "doc", id: "howto/v2/index" },
          collapsible: true,
          collapsed: true,
          items: [
            "howto/v2/add-custom-record",
            "howto/v2/add-wallet-address",
            "howto/v2/decentralized_website",
            "howto/v2/link-dns-name",
            "howto/v2/registration",
            "howto/v2/set-avatar",
            "howto/v2/set-primary-name",
            "howto/v2/set-record",
            "howto/v2/transfer-name",
          ],
        },
      ],
    },
    {
      type: "html",
      className: "sidebar-divider",
      value: "<div/>"
    },
    {
      type: "category",
      label: "Developer Basics",
      link: { type: "doc", id: "dev-basics/index" },
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: "category",
          label: "Namewrapper",
          link: { type: "doc", id: "dev-basics/namewrapper/index" },
          collapsible: true,
          collapsed: true,
          items: [
            "dev-basics/namewrapper/overview",
            "dev-basics/namewrapper/states",
            "dev-basics/namewrapper/fuses",
            "dev-basics/namewrapper/expiry",
            "dev-basics/namewrapper/approved-operators",
            {
              type: "category",
              label: "Use-Cases",
              link: { type: "doc", id: "dev-basics/namewrapper/use-cases/index" },
              collapsible: true,
              collapsed: false,
              items: [
                "dev-basics/namewrapper/use-cases/nft-holders",
                "dev-basics/namewrapper/use-cases/sell-rent-subnames",
                "dev-basics/namewrapper/use-cases/issue-tickets",
                "dev-basics/namewrapper/use-cases/lock-records",
               ],
            },
           ],
        },
	{
		type: "category",
		label: "Integration",
		link: { type: "doc", id: "dev-basics/integration/index" },
		collapsible: true,
		collapsed: true,
		items: [
			"dev-basics/integration/quick-cheatsheet",
		],
	},
        "dev-basics/namehash",
      ],
    },
  ],
};

module.exports = sidebars;
