/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
tutorialSidebar: [    {
  type: 'html',
  value:
    '<a class="navbar__brand sidebar__brand" href="/"><div class="navbar__logo"><img src="/img/enslogo_new.svg" alt="ENS Logo"></div>DNS to ENS<span><span></a>',
    defaultStyle: true
},{type: 'autogenerated', dirName: '.'}],

//  tutorialSidebar: [
//	  "intro",
//    {
//      type: "html",
//      className: "sidebar-divider",
//      value: "<div/>"
//    },
//  ],
};

module.exports = sidebars;
